import subprocess, os, sys, re, json
from handle_json import byteify as byteify
from read_eplant_snps import load_entry
import dpath.util

'''
curl -X POST -F FASTAseq="MGTHINFNNLGGGGHPGGEGSSNQMKPTGSVMPLARQSSVYSLTFDELQNTLGGPGKDFGSMNMDELLKSIWTAEEAQAMAMTSAPAATAVAQPGAGIPPPGGNLQRQGSLTLPRTISQKTVDEVWKCLITKDGNMEGSSGGGGESNVPPGRQQTLGEMTLEEFLFRAGVVREDNCVQQMGQVNGNNNNGFYGNSTAAGGLGFGFGQPNQNSITFNGTNDSMILNQPPGLGLKMGGTMQQQQQQQQLLQQQQQQMQQLNQPHPQQRLPQTIFPKQANVAFSAPVNITNKGFAGAANNSINNNNGLASYGGTGVTVAATSPGTSSAENNSLSPVPYVLNRGRRSNTGLEKVIERRQRRMIKNRESAARSRARKQAYTLELEAEIEKLKKTNQELQKKQAEMVEMQKNELKETSKRPWGSKRQCLRRTLTGPW" http://bar.utoronto.ca/eplant/cgi-bin/CDDannot.cgi > text.out
'''

url = "http://bar.utoronto.ca/eplant/cgi-bin/CDDannot.cgi"

def decode_json(tata):
	'''  '''
    cheese = byteify(json.loads(tata))
    out_var = dpath.util.get(cheese, '/DNA binding site_269855')
    return out_var

def pull_cdd_bar(seqs):
	'''   '''
	for i in seqs:
		sequence = "FASTAseq=" + i
		data = subprocess.check_output(["curl", "-X", "POST", "-F", sequence, url])
		outfile = decode_json(data)
		print outfile	


pull_cdd_bar(["MGTHINFNNLGGGGHPGGEGSSNQMKPTGSVMPLARQSSVYSLTFDELQNTLGGPGKDFGSMNMDELLKSIWTAEEAQAMAMTSAPAATAVAQPGAGIPPPGGNLQRQGSLTLPRTISQKTVDEVWKCLITKDGNMEGSSGGGGESNVPPGRQQTLGEMTLEEFLFRAGVVREDNCVQQMGQVNGNNNNGFYGNSTAAGGLGFGFGQPNQNSITFNGTNDSMILNQPPGLGLKMGGTMQQQQQQQQLLQQQQQQMQQLNQPHPQQRLPQTIFPKQANVAFSAPVNITNKGFAGAANNSINNNNGLASYGGTGVTVAATSPGTSSAENNSLSPVPYVLNRGRRSNTGLEKVIERRQRRMIKNRESAARSRARKQAYTLELEAEIEKLKKTNQELQKKQAEMVEMQKNELKETSKRPWGSKRQCLRRTLTGPW"])


